### ISSUE TITLE
项目中部分功能及体验问题

### ISSUE THREAD

**Issue by qinchangbiao** [Jsonjia/zjp-wandroid-master#1]
作者你好，首页上划体验不是很好，上滑是banner应该跟着向上滑动，再根据距离判断吸顶效果
部分功能为完成，如广场tab中顶部体系和导航未实现点击切换，列表到详情跳转链接及收藏未做，首页-文章列表的文章详情title未处理，出现转义符等问题，公众号tab文章列表跳转链接未做，切换后公众号文章列表显示问题，如公众号鸿洋列表刷到最底部，切换到郭霖（个人感觉应该从郭霖的顶部显示）项目做的不错！

**Comment by Jsonjia** [comment]
首先感谢你提出的宝贵意见，现反馈如下：
1.首页我是故意不让banner跟随一起滚动的；
2.tab导航点击事件确实没加，后期更新的时候，会加上；
3.首页出现转义符，这个不是bug，只是细节问题，可能我没太在意；
4.你提的意见很宝贵，后期我会修复的，谢谢你对我评价

**Comment by Jsonjia** [comment]
> 作者你好，首页上划体验不是很好，上滑是banner应该跟着向上滑动，再根据距离判断吸顶效果
> 部分功能为完成，如广场tab中顶部体系和导航未实现点击切换，列表到详情跳转链接及收藏未做，首页-文章列表的文章详情title未处理，出现转义符等问题，公众号tab文章列表跳转链接未做，切换后公众号文章列表显示问题，如公众号鸿洋列表刷到最底部，切换到郭霖（个人感觉应该从郭霖的顶部显示）项目做的不错！

首先感谢你提出的宝贵意见，现反馈如下：
1.首页我是故意不让banner跟随一起滚动的；
2.tab导航点击事件确实没加，后期更新的时候，会加上；
3.首页出现转义符，这个不是bug，只是细节问题，可能我没太在意；
4.你提的意见很宝贵，后期我会修复的，谢谢你对我评价

**Comment by Jsonjia** [comment]
> 作者你好，首页上划体验不是很好，上滑是banner应该跟着向上滑动，再根据距离判断吸顶效果
> 部分功能为完成，如广场tab中顶部体系和导航未实现点击切换，列表到详情跳转链接及收藏未做，首页-文章列表的文章详情title未处理，出现转义符等问题，公众号tab文章列表跳转链接未做，切换后公众号文章列表显示问题，如公众号鸿洋列表刷到最底部，切换到郭霖（个人感觉应该从郭霖的顶部显示）项目做的不错！

你好，刚刚看到你是10天前给我提的这个问题，我今天才看到，不好意思。
首先感谢你提出的宝贵意见，现反馈如下：

**不改动**：

首页我是故意不让banner跟随一起滚动的，所以首页依然保持这种效果；

**修复**
1. tab导航点击事件;
2. 公众号tab文章列表跳转链接.

**优化**

1.文章详情标题出现转义符;
2.切换后公众号文章列表显示不显示第一条问题。
3.更新constraintlayout版本号为2.0.1，弃用测试版等；
4.修复若干已知bug。

新版本已发布！
如有问题可继续反馈，感谢监督，共勉
