### ISSUE TITLE
Fragment重叠的问题

### ISSUE THREAD

**Issue by xuzhoude** [Jsonjia/zjp-wandroid-master#2]
开发者选项中开启了不保留后台活动，进入应用切换nav,再按home键进入后台，重新进入应用，切换nav,会出现Fragment重叠。

**Comment by Jsonjia** [comment]
是必现吗？还是大概率出现

**Comment by Jsonjia** [comment]
> 开发者选项中开启了不保留后台活动，进入应用切换nav,再按home键进入后台，重新进入应用，切换nav,会出现Fragment重叠。

是必现吗？还是大概率出现

**Comment by Jsonjia** [comment]
> 开发者选项中开启了不保留后台活动，进入应用切换nav,再按home键进入后台，重新进入应用，切换nav,会出现Fragment重叠。

你好，问题已经修复，包已经更新，如再有问题，可在反馈
